addSbtPlugin("com.github.sbt"            % "sbt-native-packager"       % "1.9.11")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"              % "0.10.4")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.5.0")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                   % "0.4.3")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"               % "0.6.4")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"             % "0.11.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"                 % "1.5.6")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"           % "1.1.1")
addSbtPlugin("nl.gn0s1s"                 % "sbt-dotenv"                % "3.0.0")
addSbtPlugin("io.spray"                  % "sbt-revolver"              % "0.9.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.4.2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"             % "2.0.6")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"              % "2.1.0")
addDependencyTreePlugin
